import type { Metadata } from "next";
import "./globals.css";
import { Outfit, Geist_Mono } from "next/font/google"; // Use Outfit for a premium, clean Fintech look

const fontSans = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const fontMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import QueryProvider from "@/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { NotificationListener } from "@/components/notification-listener";

import { ThemeProvider } from "@/components/theme-provider";
import { LanguageProvider } from "@/contexts/language-context";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <LanguageProvider>
            <QueryProvider>
              {children}
              <Toaster />
              <NotificationListener />
            </QueryProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
