'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Locale = 'en' | 'pt' | 'es';

interface LanguageContextType {
    locale: Locale;
    setLocale: (locale: Locale) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        'errors.descriptionRequired': 'Description is required',
        'errors.amountRequired': 'Amount must be greater than 0.01',
        'errors.categoryRequired': 'Category is required',
        'errors.installmentsMin': 'Installments must be at least 1',
        'dashboard.welcome': 'Welcome',
        'dashboard.transactions': 'Transactions',
        'dashboard.friends': 'Friends',
        'dashboard.invitations': 'Invitations',
        'dashboard.logout': 'Logout',
        'dashboard.totalIncome': 'Total Income',
        'dashboard.totalExpense': 'Total Expense',
        'dashboard.balance': 'Balance',
        'dashboard.expensesByCategory': 'Expenses by Category',
        'dashboard.evolution': 'Financial Evolution',
        'dashboard.noExpenses': 'No expenses yet',
        'common.loading': 'Loading...',
        'common.error': 'Error',
        'common.confirm': 'Confirm',
        'common.cancel': 'Cancel',
        'common.processing': 'Processing...',
        'common.restore': 'Restore',
        'nav.dashboard': 'Dashboard',
        'nav.transactions': 'Transactions',
        'nav.friends': 'Friends',
        'nav.logout': 'Logout',
        'notifications.title': 'Notifications',
        'notifications.empty': 'No new notifications',
        'notifications.friendRequests': 'Friend Requests',
        'notifications.transactionInvites': 'Transaction Invites',
        'notifications.invitedYou': 'invited you to split:',
        'notifications.accept': 'Accept',
        'notifications.reject': 'Reject',
        'notifications.friendRequestUpdated': 'Friend request updated',
        'notifications.invitationUpdated': 'Invitation updated',
        'notifications.clearAll': 'Clear All',
        'notifications.allDeleted': 'All notifications cleared',
        'transactions.title': 'Transactions',
        'transactions.addTitle': 'Add New Transaction',
        'transactions.editTitle': 'Edit Transaction',
        'transactions.description': 'Description',
        'transactions.descriptionPlaceholder': 'Transaction description',
        'transactions.amount': 'Amount',
        'transactions.type': 'Type',
        'transactions.select': 'Select',
        'transactions.income': 'Income',
        'transactions.expense': 'Expense',
        'transactions.type.INCOME': 'Income',
        'transactions.type.EXPENSE': 'Expense',
        'transactions.date': 'Date',
        'transactions.category': 'Category',
        'transactions.categoryPlaceholder': 'Ex: Food, Rent',
        'transactions.installments': 'Installments',
        'transactions.monthlyFixed': 'Monthly fixed',
        'transactions.monthlyFixedDescription': 'This transaction will repeat automatically every month with the same description and amount',
        'transactions.shareWithFriends': 'Share with friends',
        'transactions.shareWithFriendsDescription': 'Split the cost of this transaction with your friends. Each person will pay their share',
        'transactions.save': 'Save',
        'transactions.saving': 'Saving...',
        'transactions.update': 'Update',
        'transactions.updating': 'Updating...',
        'transactions.clear': 'Clear',
        'transactions.revert': 'Revert changes',
        'transactions.youPay': 'You pay:',
        'transactions.filters': 'Filters:',
        'transactions.exportCSV': 'Export CSV',
        'transactions.allTypes': 'All Types',
        'transactions.month': 'Month',
        'transactions.year': 'Year',
        'transactions.today': 'Today',
        'transactions.acceptAll': 'Accept All',
        'transactions.rejectAll': 'Reject All',
        'transactions.noTransactions': 'No transactions found for the selected filters.',
        'transactions.table.date': 'Date',
        'transactions.table.description': 'Description',
        'transactions.table.category': 'Category',
        'transactions.table.type': 'Type',
        'transactions.table.amount': 'Amount',
        'transactions.table.status': 'Status',
        'transactions.table.users': 'Users',
        'transactions.table.actions': 'Actions',
        'transactions.shared': 'Shared',
        'transactions.fixed': 'Fixed',
        'transactions.total': 'Total',
        'transactions.myShare': 'My Share',
        'transactions.status.pending': 'PENDING',
        'transactions.status.accepted': 'ACCEPTED',
        'transactions.status.rejected': 'REJECTED',
        'transactions.status.unknown': 'UNKNOWN',
        'transactions.confirmDeleteTitle': 'Delete Transaction',
        'transactions.confirmDeleteDesc': 'Are you sure you want to delete this transaction? This action cannot be undone.',
        'transactions.confirmLeaveTitle': 'Leave Transaction',
        'transactions.confirmLeaveDesc': 'Are you sure you want to leave this shared transaction?',
        'transactions.confirmRejectTitle': 'Reject Invitation',
        'transactions.confirmRejectDesc': 'Are you sure you want to reject the invitation for this transaction?',
        'transactions.addParticipants': 'Add Participants',
        'transactions.searchFriendsPlaceholder': 'Search friend or type name...',
        'transactions.friend': 'Friend',
        'transactions.external': 'External',
        'transactions.addFriendButton': 'Add Friend',
        'transactions.requestSent': 'Request Sent',
        'transactions.stopRecurrenceTitle': 'End Recurrence',
        'transactions.stopRecurrenceDesc': 'Choose the final date for this recurring transaction. Past history will be kept.',
        'transactions.goToOriginal': 'Go to original transaction',
        'transactions.navigatedToOriginal': 'Navigated to original transaction date',
        'transactions.excludedOccurrences': 'Excluded Occurrences',
        'transactions.deleteRecurringTitle': 'Delete Recurring Transaction',
        'transactions.deleteRecurringDesc': 'This is a recurring transaction. Do you want to delete only this occurrence or the entire series?',
        'transactions.deleteSingle': 'Delete only this occurrence',
        'transactions.deleteAll': 'Delete entire series',
        'transactions.add': 'Add',
        'transactions.nonRegistered': '(Non-registered)',
        'transactions.selectedParticipants': 'Selected Participants',
        'transactions.reinvite': 'Re-invite',
        'transactions.pending': 'Pending',
        'transactions.rejected': 'Rejected',
        'transactions.categoryInputPlaceholder': 'Ex: Food, Rent',
        'transactions.suggested': 'Suggested',
        'transactions.searching': 'Searching...',
        'transactions.noCategoriesFound': 'No categories found',
        'transactions.relevant': 'Relevant',
        'transactions.chooseColor': 'Choose category color',
        'categories.headerTitle': 'Category Management',
        'categories.headerDescription': 'Customize how your categories appear in transactions and reports.',
        'categories.createNewTitle': 'Create New Category',
        'categories.createNewDescription': 'Add a new category.',
        'categories.labelColor': 'Color',
        'categories.labelName': 'Name',
        'categories.placeholderName': 'e.g., Groceries',
        'categories.buttonCreate': 'Create Category',
        'categories.colorsTitle': 'My Saved Colors',
        'categories.colorsDescription': 'Manage your custom colors. Drag and drop to reorder the palette.',
        'categories.colorsLoading': 'Loading colors...',
        'categories.tooltipSystemColor': 'System color (cannot delete) - Drag to reorder',
        'categories.tooltipCustomColor': 'Custom color - Drag to reorder',
        'categories.tooltipDeleteColor': 'Delete color',
        'categories.errorNameRequired': 'Category name is required',
        'categories.successCreated': 'Category created successfully',
        'categories.errorCreate': 'Failed to create category',
        'categories.successDeleted': 'Category deleted successfully',
        'categories.errorDelete': 'Failed to delete category',
        'categories.badgeSystem': 'System',
        'categories.deleteDialogTitle': 'Delete Category',
        'categories.deleteDialogDescription': 'Are you sure you want to delete this category? This action cannot be undone.',
        'categories.successColorUpdated': 'Category color updated',
        'categories.errorUpdateColor': 'Failed to update color',
        'categories.errorSaveColorOrder': 'Failed to save color order',
        'categories.successColorDeleted': 'Color deleted',
        'categories.errorDeleteColor': 'Failed to delete color',
        'transactions.searchPlaceholder': 'Search...',
        'transactions.searchField.description': 'Description',
        'transactions.searchField.category': 'Category',
        'transactions.searchField.status': 'Status',
        'common.reset': 'Reset',
        'transactions.filter.allRecurring': 'All Occurrences',
        'transactions.filter.onlyRecurring': 'Recurring Only',
        'transactions.filter.onlyOneTime': 'One-time Only',
        'transactions.filter.allShared': 'All Transactions',
        'transactions.filter.onlyShared': 'Shared Only',
        'transactions.filter.onlyPrivate': 'Private Only',
    },
    pt: {
        'errors.descriptionRequired': 'A descrição é obrigatória',
        'errors.amountRequired': 'O valor deve ser maior que 0,01',
        'errors.categoryRequired': 'A categoria é obrigatória',
        'errors.installmentsMin': 'O número de parcelas deve ser pelo menos 1',
        'dashboard.welcome': 'Bem-vindo',
        'dashboard.transactions': 'Transações',
        'dashboard.friends': 'Amigos',
        'dashboard.invitations': 'Convites',
        'dashboard.logout': 'Sair',
        'dashboard.totalIncome': 'Receita Total',
        'dashboard.totalExpense': 'Despesa Total',
        'dashboard.balance': 'Saldo',
        'dashboard.expensesByCategory': 'Despesas por Categoria',
        'dashboard.evolution': 'Evolução Financeira',
        'dashboard.noExpenses': 'Sem despesas ainda',
        'common.loading': 'Carregando...',
        'common.error': 'Erro',
        'common.confirm': 'Confirmar',
        'common.cancel': 'Cancelar',
        'common.processing': 'Processando...',
        'common.restore': 'Restaurar',
        'nav.dashboard': 'Dashboard',
        'nav.transactions': 'Transações',
        'nav.friends': 'Amigos',
        'nav.logout': 'Sair',
        'notifications.title': 'Notificações',
        'notifications.empty': 'Nenhuma nova notificação',
        'notifications.friendRequests': 'Solicitações de Amizade',
        'notifications.transactionInvites': 'Convites de Transação',
        'notifications.invitedYou': 'convidou você para dividir:',
        'notifications.accept': 'Aceitar',
        'notifications.reject': 'Rejeitar',
        'notifications.friendRequestUpdated': 'Solicitação de amizade atualizada',
        'notifications.invitationUpdated': 'Convite atualizado',
        'notifications.clearAll': 'Limpar Tudo',
        'notifications.allDeleted': 'Todas as notificações foram limpas',
        'transactions.title': 'Transações',
        'transactions.addTitle': 'Adicionar Nova Transação',
        'transactions.editTitle': 'Editar Transação',
        'transactions.description': 'Descrição',
        'transactions.descriptionPlaceholder': 'Descrição da transação',
        'transactions.amount': 'Valor',
        'transactions.type': 'Tipo',
        'transactions.select': 'Selecione',
        'transactions.income': 'Receita',
        'transactions.expense': 'Despesa',
        'transactions.type.INCOME': 'Receita',
        'transactions.type.EXPENSE': 'Despesa',
        'transactions.date': 'Data',
        'transactions.category': 'Categoria',
        'transactions.categoryPlaceholder': 'Ex: Alimentação, Aluguel',
        'transactions.installments': 'Parcelas',
        'transactions.monthlyFixed': 'Fixo mensal',
        'transactions.monthlyFixedDescription': 'Esta transação se repetirá automaticamente todos os meses com a mesma descrição e valor',
        'transactions.shareWithFriends': 'Compartilhar com amigos',
        'transactions.shareWithFriendsDescription': 'Divida o custo desta transação com seus amigos. Cada pessoa pagará sua parte',
        'transactions.save': 'Salvar',
        'transactions.saving': 'Salvando...',
        'transactions.update': 'Alterar',
        'transactions.updating': 'Alterando...',
        'transactions.clear': 'Limpar',
        'transactions.revert': 'Revertar alterações',
        'transactions.youPay': 'Você paga:',
        'transactions.filters': 'Filtros:',
        'transactions.exportCSV': 'Exportar CSV',
        'transactions.allTypes': 'Todos os Tipos',
        'transactions.month': 'Mês',
        'transactions.year': 'Ano',
        'transactions.today': 'Hoje',
        'transactions.acceptAll': 'Aceitar Todos',
        'transactions.rejectAll': 'Recusar Todos',
        'transactions.noTransactions': 'Nenhuma transação encontrada para os filtros selecionados.',
        'transactions.table.date': 'Data',
        'transactions.table.description': 'Descrição',
        'transactions.table.category': 'Categoria',
        'transactions.table.type': 'Tipo',
        'transactions.table.amount': 'Valor',
        'transactions.table.status': 'Status',
        'transactions.table.users': 'Usuários',
        'transactions.table.actions': 'Ações',
        'transactions.shared': 'Compartilhado',
        'transactions.fixed': 'Fixo',
        'transactions.total': 'Total',
        'transactions.myShare': 'Minha Parte',
        'transactions.status.pending': 'PENDENTE',
        'transactions.status.accepted': 'ACEITO',
        'transactions.status.rejected': 'REJEITADO',
        'transactions.status.unknown': 'DESCONHECIDO',
        'transactions.confirmDeleteTitle': 'Apagar Transação',
        'transactions.confirmDeleteDesc': 'Tem certeza que deseja apagar esta transação? Esta ação não pode ser desfeita.',
        'transactions.confirmLeaveTitle': 'Sair da Transação',
        'transactions.confirmLeaveDesc': 'Tem certeza que deseja sair desta transação compartilhada?',
        'transactions.confirmRejectTitle': 'Recusar Convite',
        'transactions.confirmRejectDesc': 'Tem certeza que deseja recusar o convite para esta transação?',
        'transactions.addParticipants': 'Adicionar Participantes',
        'transactions.searchFriendsPlaceholder': 'Buscar amigo ou digitar nome...',
        'transactions.friend': 'Amigo',
        'transactions.external': 'Externo',
        'transactions.addFriendButton': 'Adicionar Amigo',
        'transactions.requestSent': 'Solicitação Enviada',
        'transactions.add': 'Adicionar',
        'transactions.nonRegistered': '(Não registrado)',
        'transactions.selectedParticipants': 'Participantes Selecionados',
        'transactions.stopRecurrenceTitle': 'Parar Recorrência',
        'transactions.stopRecurrenceDesc': 'Escolha a data final para esta transação. O histórico anterior será mantido.',
        'transactions.goToOriginal': 'Ir para transação original',
        'transactions.navigatedToOriginal': 'Navegado para a data da transação original',
        'transactions.excludedOccurrences': 'Ocorrências Excluídas',
        'transactions.deleteRecurringTitle': 'Excluir Transação Recorrente',
        'transactions.deleteRecurringDesc': 'Esta é uma transação recorrente. Deseja excluir apenas esta ocorrência ou toda a série?',
        'transactions.deleteSingle': 'Excluir apenas esta ocorrência',
        'transactions.deleteAll': 'Excluir toda a série',
        'transactions.reinvite': 'Re-convidar',
        'transactions.pending': 'Pendente',
        'transactions.rejected': 'Rejeitado',
        'transactions.categoryInputPlaceholder': 'Ex: Alimentação, Aluguel',
        'transactions.suggested': 'Sugerido',
        'transactions.searching': 'Buscando...',
        'transactions.noCategoriesFound': 'Nenhuma categoria encontrada',
        'transactions.relevant': 'Relevante',
        'transactions.chooseColor': 'Escolher cor da categoria',
        'categories.headerTitle': 'Gerenciamento de Categorias',
        'categories.headerDescription': 'Personalize como suas categorias aparecem em transações e relatórios.',
        'categories.createNewTitle': 'Criar Nova Categoria',
        'categories.createNewDescription': 'Adicione uma nova categoria.',
        'categories.labelColor': 'Cor',
        'categories.labelName': 'Nome',
        'categories.placeholderName': 'Ex: Alimentação',
        'categories.buttonCreate': 'Criar Categoria',
        'categories.colorsTitle': 'Minhas Cores Salvas',
        'categories.colorsDescription': 'Gerencie suas cores personalizadas. Arraste e solte para reordenar a paleta.',
        'categories.colorsLoading': 'Carregando cores...',
        'categories.tooltipSystemColor': 'Cor do sistema (não pode apagar) - Arraste para reordenar',
        'categories.tooltipCustomColor': 'Cor personalizada - Arraste para reordenar',
        'categories.tooltipDeleteColor': 'Apagar cor',
        'categories.errorNameRequired': 'Nome da categoria é obrigatório',
        'categories.successCreated': 'Categoria criada com sucesso',
        'categories.errorCreate': 'Falha ao criar categoria',
        'categories.successDeleted': 'Categoria apagada com sucesso',
        'categories.errorDelete': 'Falha ao apagar categoria',
        'categories.badgeSystem': 'Sistema',
        'categories.deleteDialogTitle': 'Apagar Categoria',
        'categories.deleteDialogDescription': 'Tem certeza que deseja apagar esta categoria? Esta ação não pode ser desfeita.',
        'categories.successColorUpdated': 'Cor da categoria atualizada',
        'categories.errorUpdateColor': 'Falha ao atualizar cor',
        'categories.errorSaveColorOrder': 'Falha ao salvar ordem das cores',
        'categories.successColorDeleted': 'Cor apagada',
        'categories.errorDeleteColor': 'Falha ao apagar cor',
        'transactions.searchPlaceholder': 'Buscar...',
        'transactions.searchField.description': 'Descrição',
        'transactions.searchField.category': 'Categoria',
        'transactions.searchField.status': 'Status',
        'common.reset': 'Resetar',
        'transactions.filter.allRecurring': 'Todas as Ocorrências',
        'transactions.filter.onlyRecurring': 'Apenas Recorrentes',
        'transactions.filter.onlyOneTime': 'Apenas Pontuais',
        'transactions.filter.allShared': 'Todas as Transações',
        'transactions.filter.onlyShared': 'Apenas Compartilhadas',
        'transactions.filter.onlyPrivate': 'Apenas Privadas',
    },
    es: {
        'errors.descriptionRequired': 'La descripción es obligatoria',
        'errors.amountRequired': 'El monto debe ser mayor a 0.01',
        'errors.categoryRequired': 'La categoría es obligatoria',
        'errors.installmentsMin': 'El número de cuotas debe ser al menos 1',
        'dashboard.welcome': 'Bienvenido',
        'dashboard.transactions': 'Transacciones',
        'dashboard.friends': 'Amigos',
        'dashboard.invitations': 'Invitaciones',
        'dashboard.logout': 'Cerrar sesión',
        'dashboard.totalIncome': 'Ingresos Totales',
        'dashboard.totalExpense': 'Gastos Totales',
        'dashboard.balance': 'Saldo',
        'dashboard.expensesByCategory': 'Gastos por Categoría',
        'dashboard.evolution': 'Evolución Financiera',
        'dashboard.noExpenses': 'Sin gastos aún',
        'common.loading': 'Cargando...',
        'common.error': 'Error',
        'common.confirm': 'Confirmar',
        'common.cancel': 'Cancelar',
        'common.processing': 'Procesando...',
        'common.restore': 'Restaurar',
        'nav.dashboard': 'Tablero',
        'nav.transactions': 'Transacciones',
        'nav.friends': 'Amigos',
        'nav.logout': 'Cerrar sesión',
        'notifications.title': 'Notificaciones',
        'notifications.empty': 'No hay notificaciones nuevas',
        'notifications.friendRequests': 'Solicitudes de Amistad',
        'notifications.transactionInvites': 'Invitaciones de Transacción',
        'notifications.invitedYou': 'te invitó a dividir:',
        'notifications.accept': 'Aceptar',
        'notifications.reject': 'Rechazar',
        'notifications.friendRequestUpdated': 'Solicitud de amistad actualizada',
        'notifications.invitationUpdated': 'Invitación actualizada',
        'notifications.clearAll': 'Limpiar Todo',
        'notifications.allDeleted': 'Todas las notificaciones borradas',
        'transactions.title': 'Transacciones',
        'transactions.addTitle': 'Agregar Nueva Transacción',
        'transactions.editTitle': 'Editar Transacción',
        'transactions.description': 'Descripción',
        'transactions.descriptionPlaceholder': 'Descripción de la transacción',
        'transactions.amount': 'Monto',
        'transactions.type': 'Tipo',
        'transactions.select': 'Seleccione',
        'transactions.income': 'Ingreso',
        'transactions.expense': 'Gasto',
        'transactions.type.INCOME': 'Ingreso',
        'transactions.type.EXPENSE': 'Gasto',
        'transactions.date': 'Fecha',
        'transactions.category': 'Categoría',
        'transactions.categoryPlaceholder': 'Ej: Comida, Alquiler',
        'transactions.installments': 'Cuotas',
        'transactions.monthlyFixed': 'Fijo mensual',
        'transactions.monthlyFixedDescription': 'Esta transacción se repetirá automáticamente todos los meses con la misma descripción y valor',
        'transactions.shareWithFriends': 'Compartir con amigos',
        'transactions.shareWithFriendsDescription': 'Divide el costo de esta transacción con tus amigos. Cada persona pagará su parte',
        'transactions.save': 'Guardar',
        'transactions.saving': 'Guardando...',
        'transactions.update': 'Actualizar',
        'transactions.updating': 'Actualizando...',
        'transactions.clear': 'Limpiar',
        'transactions.revert': 'Revertir cambios',
        'transactions.youPay': 'Tú pagas:',
        'transactions.filters': 'Filtros:',
        'transactions.exportCSV': 'Exportar CSV',
        'transactions.allTypes': 'Todos los Tipos',
        'transactions.month': 'Mes',
        'transactions.year': 'Año',
        'transactions.today': 'Hoy',
        'transactions.acceptAll': 'Aceptar Todos',
        'transactions.rejectAll': 'Rechazar Todos',
        'transactions.noTransactions': 'No se encontraron transacciones para los filtros seleccionados.',
        'transactions.table.date': 'Fecha',
        'transactions.table.description': 'Descripción',
        'transactions.table.category': 'Categoría',
        'transactions.table.type': 'Tipo',
        'transactions.table.amount': 'Monto',
        'transactions.table.status': 'Estado',
        'transactions.table.users': 'Usuarios',
        'transactions.table.actions': 'Acciones',
        'transactions.shared': 'Compartido',
        'transactions.fixed': 'Fijo',
        'transactions.total': 'Total',
        'transactions.myShare': 'Mi Parte',
        'transactions.status.pending': 'PENDIENTE',
        'transactions.status.accepted': 'ACEPTADO',
        'transactions.status.rejected': 'RECHAZADO',
        'transactions.status.unknown': 'DESCONOCIDO',
        'transactions.confirmDeleteTitle': 'Eliminar Transacción',
        'transactions.confirmDeleteDesc': '¿Estás seguro de que quieres eliminar esta transacción? Esta acción no se puede deshacer.',
        'transactions.confirmLeaveTitle': 'Salir de la Transacción',
        'transactions.confirmLeaveDesc': '¿Estás seguro de que quieres salir de esta transacción compartida?',
        'transactions.confirmRejectTitle': 'Rechazar Invitación',
        'transactions.confirmRejectDesc': '¿Estás seguro de que quieres rechazar la invitación para esta transacción?',
        'transactions.addParticipants': 'Agregar Participantes',
        'transactions.searchFriendsPlaceholder': 'Buscar amigo o escribir nombre...',
        'transactions.friend': 'Amigo',
        'transactions.external': 'Externo',
        'transactions.addFriendButton': 'Agregar Amigo',
        'transactions.requestSent': 'Solicitud Enviada',
        'transactions.add': 'Agregar',
        'transactions.nonRegistered': '(No registrado)',
        'transactions.selectedParticipants': 'Participantes Selecionados',
        'transactions.reinvite': 'Re-invitar',
        'transactions.pending': 'Pendiente',
        'transactions.stopRecurrenceTitle': 'Terminar Recurrencia',
        'transactions.stopRecurrenceDesc': 'Elija la fecha final para esta transacción recurrente. El historial pasado se mantendrá.',
        'transactions.goToOriginal': 'Ir a la transacción original',
        'transactions.navigatedToOriginal': 'Navegado a la fecha de la transacción original',
        'transactions.excludedOccurrences': 'Ocurrencias Excluidas',
        'transactions.deleteRecurringTitle': 'Eliminar Transacción Recurrente',
        'transactions.deleteRecurringDesc': 'Esta es una transacción recurrente. ¿Desea eliminar solo esta ocurrencia o toda la serie?',
        'transactions.deleteSingle': 'Eliminar solo esta ocurrencia',
        'transactions.deleteAll': 'Eliminar toda la serie',
        'transactions.rejected': 'Rechazado',
        'transactions.categoryInputPlaceholder': 'Ej: Comida, Alquiler',
        'transactions.suggested': 'Sugerido',
        'transactions.searching': 'Buscando...',
        'transactions.noCategoriesFound': 'No se encontró ninguna categoría',
        'transactions.relevant': 'Relevante',
        'transactions.chooseColor': 'Elegir color de categoría',
        'categories.headerTitle': 'Gestión de Categorías',
        'categories.headerDescription': 'Personaliza cómo aparecen tus categorías en transacciones e informes.',
        'categories.createNewTitle': 'Crear Nueva Categoría',
        'categories.createNewDescription': 'Añadir una nueva categoría.',
        'categories.labelColor': 'Color',
        'categories.labelName': 'Nombre',
        'categories.placeholderName': 'Ej: Comida',
        'categories.buttonCreate': 'Crear Categoría',
        'categories.colorsTitle': 'Mis Colores Guardados',
        'categories.colorsDescription': 'Administra tus colores personalizados. Arrastra y suelta para reordenar la paleta.',
        'categories.colorsLoading': 'Cargando colores...',
        'categories.tooltipSystemColor': 'Color del sistema (no eliminar) - Arrastrar para reordenar',
        'categories.tooltipCustomColor': 'Color personalizado - Arrastrar para reordenar',
        'categories.tooltipDeleteColor': 'Eliminar color',
        'categories.errorNameRequired': 'El nombre de la categoría es obligatorio',
        'categories.successCreated': 'Categoría creada con éxito',
        'categories.errorCreate': 'Error al crear la categoría',
        'categories.successDeleted': 'Categoría eliminada con éxito',
        'categories.errorDelete': 'Error al eliminar la categoría',
        'categories.badgeSystem': 'Sistema',
        'categories.deleteDialogTitle': 'Eliminar Categoría',
        'categories.deleteDialogDescription': '¿Estás seguro de que deseas eliminar esta categoría? Esta acción no se puede deshacer.',
        'categories.successColorUpdated': 'Color de categoría actualizado',
        'categories.errorUpdateColor': 'Error al actualizar color',
        'categories.errorSaveColorOrder': 'Error al guardar el orden de colores',
        'categories.successColorDeleted': 'Color eliminado',
        'categories.errorDeleteColor': 'Error al eliminar color',
        'transactions.searchPlaceholder': 'Buscar...',
        'transactions.searchField.description': 'Descripción',
        'transactions.searchField.category': 'Categoría',
        'transactions.searchField.status': 'Estado',
        'common.reset': 'Reiniciar',
        'transactions.filter.allRecurring': 'Todas las Ocurrencias',
        'transactions.filter.onlyRecurring': 'Solo Recurrentes',
        'transactions.filter.onlyOneTime': 'Solo Únicas',
        'transactions.filter.allShared': 'Todas las Transacciones',
        'transactions.filter.onlyShared': 'Solo Compartidas',
        'transactions.filter.onlyPrivate': 'Solo Privadas',
    },

};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [locale, setLocale] = useState<Locale>('pt'); // Default to PT as requested

    useEffect(() => {
        const saved = localStorage.getItem('locale') as Locale;
        if (saved) setLocale(saved);
    }, []);

    const handleSetLocale = (l: Locale) => {
        setLocale(l);
        localStorage.setItem('locale', l);
    };

    const t = (key: string) => {
        return (translations[locale] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ locale, setLocale: handleSetLocale, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
};
